name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python (for Python app)
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies (for Python app)
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests (if you have tests)
      run: |
        pytest

    - name: Lint Code (Optional, can be a step before SonarQube)
      run: |
        pip install flake8
        flake8 app.py
